# Generated by Django 3.0 on 2020-02-23 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for client contact', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('sujet', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
