# Generated by Django 3.0 on 2020-02-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicament', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateField(default=None)),
                ('etat_commande', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inscription.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsCommandeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_med', models.DecimalField(decimal_places=2, default=0.0, help_text='La quantité en carton', max_digits=10, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.CommandeModel')),
                ('id_medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicament.Medicament')),
            ],
        ),
    ]
