# Generated by Django 3.0 on 2020-02-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Type client : ', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('libelle',)},
            },
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom : ', max_length=50)),
                ('prenom', models.CharField(blank=True, help_text='Prenom(s) : ', max_length=50)),
                ('email', models.EmailField(help_text='Email : ', max_length=50)),
                ('contact', models.CharField(blank=True, help_text='Contact : ', max_length=50)),
                ('password', models.CharField(default='VAUh7WL8Jr', help_text='Mot de passe definit', max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='xmk5xU2woo', help_text='Mot de passe par defaut : xmk5xU2woo', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('ville', models.CharField(default=None, max_length=255)),
                ('x', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.TypeClient', verbose_name='libelle')),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
