# Generated by Django 3.0 on 2020-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='wMcgWj54yN', help_text='Mot de passe par defaut : wMcgWj54yN', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='u7WJD4M0ku', help_text='Mot de passe definit', max_length=50),
        ),
    ]
