# Generated by Django 3.0 on 2020-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_auto_20200223_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='LcTur3J7e5', help_text='Mot de passe par defaut : LcTur3J7e5', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='x',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='y',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='aeHl7PS71b', help_text='Mot de passe definit', max_length=50),
        ),
    ]
