# Generated by Django 3.0 on 2020-02-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20200227_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='Y3Obo3VPbL', help_text='Mot de passe par defaut : Y3Obo3VPbL', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='x',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='y',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=30),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='KLyhfBcs2c', help_text='Mot de passe definit', max_length=50),
        ),
    ]
