# Generated by Django 3.0 on 2020-02-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_auto_20200229_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='DpAw37UTux', help_text='Mot de passe par defaut : DpAw37UTux', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='9aYLKqxl2o', help_text='Mot de passe definit', max_length=50),
        ),
    ]
