# Generated by Django 3.0 on 2020-02-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0010_auto_20200229_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='qd8Z20S6FG', help_text='Mot de passe par defaut : qd8Z20S6FG', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='acLjhwOx38', help_text='Mot de passe definit', max_length=50),
        ),
    ]
