# Generated by Django 3.0 on 2020-02-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_auto_20200229_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='oeIDoxFzk5', help_text='Mot de passe par defaut : oeIDoxFzk5', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='x',
            field=models.DecimalField(decimal_places=33, default=None, max_digits=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='y',
            field=models.DecimalField(decimal_places=33, default=None, max_digits=40),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='9PIYO900sn', help_text='Mot de passe definit', max_length=50),
        ),
    ]
