# Generated by Django 3.0 on 2020-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_auto_20200229_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service_time',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='HsgITz51ED', help_text='Mot de passe par defaut : HsgITz51ED', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='earnWQQDDd', help_text='Mot de passe definit', max_length=50),
        ),
    ]
