# Generated by Django 3.0 on 2020-03-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0013_auto_20200301_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='0wRXxZOSbn', help_text='Mot de passe par defaut : 0wRXxZOSbn', max_length=255),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='password',
            field=models.CharField(default='a8HO0YqYlN', help_text='Mot de passe definit', max_length=50),
        ),
    ]
