# Generated by Django 3.0 on 2020-02-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='kilo_paquet',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20),
        ),
    ]
