# Generated by Django 3.0 on 2020-02-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_medicament_kilo_paquet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='kilo_paquet',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
        ),
    ]
